### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by Graleszczur** [Re-Host-pl/rh-core#1]
Preferably use DB Designer as a tool. Post schema in comment.

**Comment by Graleszczur** [comment]
It should contain:
Table with user data,
Table with information about user domain,
Table with DNS server info.

**Comment by Rahano** [comment]
![p1](https://user-images.githubusercontent.com/56368819/66861845-0df50000-ef90-11e9-9010-5d8a4f48b097.png)

**Comment by Graleszczur** [comment]
All acording to the plan. Accepted.
